server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.2"
      snapshot: false
  server:
    password: "youshallnotpass"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    trackStuckThresholdMs: 10000
    youtubePlaylistLoadLimit: 10
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MWEB
      - WEB
      - ANDROID_VR
      - TV
      - WEBEMBEDDED
      - MUSIC
    clientOptions:
      WEB:
        playlistLoading: true
        videoLoading: true
        searching: true
        playback: true
      MWEB:
        playlistLoading: true
        videoLoading: true
        searching: true
        playback: true
      ANDROID_VR:
        playlistLoading: true
        videoLoading: true
        searching: false
        playback: true
      TV:
        playlistLoading: false
        videoLoading: false
        searching: false
        playback: true
      WEBEMBEDDED:
        playlistLoading: false
        searching: false
        playback: true
      MUSIC:
        playback: false
        playlistLoading: false
        videoLoading: false
    oauth:
      enabled: true
    pot:
      token: "CgtLYnJKeDl1N0pJMCjW2cO8BjIKCgJERRIEEgAgKg=="
      visitorData: "MnRuJyEtJOv8LW4fImJbwY4qXcflEPdSWXwKWnQappnJt4Ee_3bFCJEUmiePXV3jvyjxMuT8pE3j-ZKoLtF-bIjo7-erKATkj38QRYgrGRsEHDC97Qk9a-tcYdXpmMQt2h6A1S325QgSsRfbfjBfBTeDq_oZBA=="
    remoteCipher:
      url: "https://cipher.kikkia.dev/"
      userAgent: "bot-discord"

logging:
  level:
    root: INFO
    lavalink: INFO
    dev.lavalink.youtube.http.YoutubeOauth2Handler: INFO
