- op: replace
  path: /spec/parentRefs/0/name
  value: public
- op: replace
  path: /spec/parentRefs/0/sectionName
  value: https
- op: replace
  path: /spec/hostnames/0
  value: bot-discord.kingbr.com.br
