apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bot-discord

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: bot-discord-web
    path: deployment.yaml
  - target:
      kind: HTTPRoute
      name: bot-discord-web
    path: httproute.yaml
