apiVersion: v1
kind: ConfigMap
metadata:
  name: lavalink-config
  namespace: bot-discord
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  application.yml: |
    server:
      port: 2333
      address: 0.0.0.0

    lavalink:
      plugins:
        - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.2"
          snapshot: false
      server:
        password: "unused-overridden-by-env"
        sources:
          youtube: false
          bandcamp: true
          soundcloud: true
          twitch: true
          vimeo: true
          http: true
          local: false
        bufferDurationMs: 400
        frameBufferDurationMs: 5000
        trackStuckThresholdMs: 10000
        youtubePlaylistLoadLimit: 10
        playerUpdateInterval: 5
        youtubeSearchEnabled: true
        soundcloudSearchEnabled: true
        gc-warnings: true

    plugins:
      youtube:
        enabled: true
        allowSearch: true
        allowDirectVideoIds: true
        allowDirectPlaylistIds: true
        clients:
          - WEB
          - MWEB
          - ANDROID_VR
          - TV
          - WEBEMBEDDED
          - MUSIC
        clientOptions:
          WEB:
            playlistLoading: true
            videoLoading: true
            searching: true
            playback: false
          MWEB:
            playlistLoading: true
            videoLoading: true
            searching: true
            playback: false
          ANDROID_VR:
            playlistLoading: true
            videoLoading: true
            searching: false
            playback: false
          TV:
            playlistLoading: false
            videoLoading: false
            searching: false
            playback: true
          WEBEMBEDDED:
            playlistLoading: false
            searching: false
            playback: true
          MUSIC:
            playback: false
            playlistLoading: false
            videoLoading: false
        oauth:
          enabled: true
          refreshToken: ${YOUTUBE_OAUTH_REFRESH_TOKEN}
          skipInitialization: true
        remoteCipher:
          url: "https://cipher.kikkia.dev/"
          userAgent: "bot-discord"

    logging:
      level:
        root: INFO
        lavalink: INFO
        dev.lavalink.youtube.http.YoutubeOauth2Handler: INFO
