---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lavalink-deezer-config
  namespace: bot-discord
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    DEEZER_ARL: AgAuZ5N9PlzG0v2ggy35QCTAvgIKX1C1dJwZ9MkZiqIVvga0ZTniptsCQdCh6GfNq4gz6TVq5zl9idlI9iVpow8zOwlnYRSmBOMcbdIniy/9C5SH6sTKSgNVrO/aOgUe2g/paEbCjdNAn912nX8ENCXTgteSUltaiYGp4l/d0/yOEWPh7lEMF8GVxnFA0EV2VXH6lTbixqROrqLBn9uS8Y+meNz8zsSvvfZLqfC+J0qUPCGoVCUM4zNBY9zn6SoVbgT4AFnGqys8pxp+8tVWV/x8A5m/UtX3sYjveQ0z3LRcxTqxG4wLE0uBlgK7LgsctCE5uqxbJs3fStXxhrcwbJrZswZd7YCmQSxzXA/enYRqjG6Eb+2pg8V5vzTdlSw0jZQkmpLErAL15sjttDpBOISWeOZAUapT6jH4nkLxWm/lCARkh2mIanpDedhG4WkHqtV1H8EUodm1/zhLrIVSGuXvMXLhulJRtdZ6NsUlyf8eJoBbVss9bq1U7Ke2SlSzbcNQbVawyp7WrwMowXDHYJcyCdfgvOTLShL3iLuEbv4jqTsFHkF+9IcZv8JHIlzhslfxnwvYZ86QacqU7b0GK93pal09VjWCC8d3ihpW7tV11sEk2Se80NaWJqtrQhJrVFU0uc/vnzSf3Y0rtsUbD9VzVNT+TAySioXshWq0xHQ1RaGLRurHyqt6Oki1zsCj0hpUiYmjrdIJOkkowfM7+iAgd2tCRntkzwVac5HnPCV1NMsDzz+NVdlIewcKs7HEHCMaOC/tdXq/JPRi+ZWBYiiG+xZzdosAxTQgm1WCk/1IJws73EcZAskKJEJNTi0TgisxXSD/Hb+PXOHrbrO7kVhtT9a+uAhZxkv2dX4QzzBRwM3rkp7QOkW3896zqfuv5OuNNC62QCGbcFZitUaD5srJwzu3jI2YXZOr3R1xR48Is1BqV18KEuT5xVUUB20QOlU=
  template:
    metadata:
      name: lavalink-deezer-config
      namespace: bot-discord
    type: Opaque
