---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lavalink-deezer-config
  namespace: bot-discord
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    DEEZER_ARL: AgAuZ5N9PlzG0v2ggy35QCTAvgIKX1C1dJwZ9MkZiqIVvga0ZTniptsCQdCh6GfNq4gz6TVq5zl9idlI9iVpow8zOwlnYRSmBOMcbdIniy/9C5SH6sTKSgNVrO/aOgUe2g/paEbCjdNAn912nX8ENCXTgteSUltaiYGp4l/d0/yOEWPh7lEMF8GVxnFA0EV2VXH6lTbixqROrqLBn9uS8Y+meNz8zsSvvfZLqfC+J0qUPCGoVCUM4zNBY9zn6SoVbgT4AFnGqys8pxp+8tVWV/x8A5m/UtX3sYjveQ0z3LRcxTqxG4wLE0uBlgK7LgsctCE5uqxbJs3fStXxhrcwbJrZswZd7YCmQSxzXA/enYRqjG6Eb+2pg8V5vzTdlSw0jZQkmpLErAL15sjttDpBOISWeOZAUapT6jH4nkLxWm/lCARkh2mIanpDedhG4WkHqtV1H8EUodm1/zhLrIVSGuXvMXLhulJRtdZ6NsUlyf8eJoBbVss9bq1U7Ke2SlSzbcNQbVawyp7WrwMowXDHYJcyCdfgvOTLShL3iLuEbv4jqTsFHkF+9IcZv8JHIlzhslfxnwvYZ86QacqU7b0GK93pal09VjWCC8d3ihpW7tV11sEk2Se80NaWJqtrQhJrVFU0uc/vnzSf3Y0rtsUbD9VzVNT+TAySioXshWq0xHQ1RaGLRurHyqt6Oki1zsCj0hpUiYmjrdIJOkkowfM7+iAgd2tCRntkzwVac5HnPCV1NMsDzz+NVdlIewcKs7HEHCMaOC/tdXq/JPRi+ZWBYiiG+xZzdosAxTQgm1WCk/1IJws73EcZAskKJEJNTi0TgisxXSD/Hb+PXOHrbrO7kVhtT9a+uAhZxkv2dX4QzzBRwM3rkp7QOkW3896zqfuv5OuNNC62QCGbcFZitUaD5srJwzu3jI2YXZOr3R1xR48Is1BqV18KEuT5xVUUB20QOlU=
    DEEZER_MASTER_DECRYPTION_KEY: AgCZyKO0Mamx+bDBNJSkegxWu+Atq6M/4odncOnDUHnST/Fd/csN3fZc2DJFHyvX7dacx6UB7XiV1Cqil0Q5V6xXH+l9j0Y3jPW23mwLhkP45QvHGt/KgEhN7306hFpNOuMVNnCzf077F9BS6L110Q92ZHE+3wMuU2xT16YHuU+4bVi2cZQ9cAKbM52p2OMsdXtStiMIRQ+Cz0zHTNvB3SQYV1CzGWJeQUN/dpZk51JFQLlkeu0jdZ6vGWuDPVu/1gsjMdZfmd6k1e9e5+O6q01PSwcab0KtK7h5yfHRMZoZuFR1ghVUUfBrasZxD/JvIsztQ3BUngMuyNyCqcrAcjrAeFJGbGPfArPh0Pi5/Sa+2H4nGvaBkibMEKpERa1KybcN6Z+9nbjKDTx0RQ8MqOp6gnVl1Qzh8WY8XObj0OWGFf75gK1LxDaTz2f0fhSD5AD0ug/aghidl2W3oxEhGRTgFQ4jqMIYxACR50VQbH1uwn7M/Inaf56DljN+XuHGZaa+dSAX+P8YHzBiH26J848UHr7n+AsjN30BhIWBX8YRMpWjSf0jPYziOooKUSHs3ivbzHoG3/3CQMH8chvHsFv6A4HNfEjL/yiJtB4OJdIJi/RTpkGhxy/HvTLZsp0t8i2AbCqlqRGeLKDaL0G3RogsAo/wGZIVY4M+oPoy4V5IAt7MiE3+bH01WggOP4Z/IiQT4dm6TyJrRwz3UrezJdUu
  template:
    metadata:
      name: lavalink-deezer-config
      namespace: bot-discord
    type: Opaque
