---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bot-discord-spotify
  namespace: bot-discord
spec:
  encryptedData:
    SPOTIFY_CLIENT_ID: AgA2N3QCbSoaj/NtFarl1ZsSTp5vXzRqwWykJ2GLhzf+AEYSfgCmTWNYxyxbOLft/rOs2KEaT2uzg81NaQKkl0Y/ZuLXYWT3Mf+0MUU94qrzbUuH3m2/D5TbC2tcq9icn8amq+0SNcWQmdMx0ZBfp4AgecMZsK24rmRzr2RPHNzj+rh1JcEc30beMAD1SyVV3+voXixBUcYUdqyvApdBpNpLGZlCOmAI8p3bxF6H9YdvcukhkZYPzZvuyNtbqWBFkIlNTw6xhCUCH5KtrIunmaBT9PBQAK0K3fo49gC3Ty4pMBxfHZo1bKglOkFaR/d4TpiNgAt5cST78OlYQpzWXrv2CfAKZKJ6/u7L3/c73QI0AV+cn770yctic38EOJLH1lQm1Zq9YtkFvhmvZQanCo8yrJBZiIICARceSIfyZ0wQU6f96ZuoWVGL/9LffTR7l7o0Afs6+W/9CpGWRGUIaQLIt/txmI0x9iLAIXLBJxjBytrXpKWKlR5II4iujpMTngrmIliqOHQxq1a4+GerURWBikPH9G3wACy6VBlF8OY1vO5eq/donwygf9LsEc/MYN+FCSfyfBcLT0Vnw1GL12r6J3fvztyE7/rvfI6IYnzb3EfdNBEz0BRFx9k8JV8xpUb/QfHb+MfiPLNGkuKdW5QUulZSHmbAwUbC/OnLMKihbMrrGv0E41X7FxSfR5q4O3FBYJxQ41aUb8GBVNlkLPB0PtpH7gpZiE9i0ljy1VjBuw==
    SPOTIFY_CLIENT_SECRET: AgAL3BKCxFJbHxxHyi0W1DkL5v25RgSU1Wid6zT/ben/F1XsrQ9XnJsRQYwkovXy+xid/jzPjM7eyDhvfo1edpBnVm1bebISO+X37/Rx8C9P9LK0LipmIMG5f3nguj/jEz0baz09XeV/OzEets9Us1GKwy8V2a5k05YyDjS+pz/JvaOLbFClEOrEcIAqUZLIWES2dRhP/L7a0FSkwie2rzDh0yZxlmFEDhK0b657aF+tRgefcxKKlmiWdjsmdQsMZ/b5J6hoh+GmCr3qapNd32DT11v6OwrNrGKNeO1q0Qnx/exqDk8KwB6oSFJBQ4qfORS6B2Jsiqumn3QDEgF/zKKmqtDlGXxkmpqFQjXFF/DuqFWJ11c085yJAMFf0SLEuxQ0Zn/91NWYF22REj3bpOF6AX+CPBIsd1V8BnzcNckOAoYUZ8fstkIKA99oJUJxQ/EihIb8VKExMaijeW+laNsyMvXL4TTBplKl1OEi4sVV3kChuV/THNO9aXYELTIw9PVM6aVnMTKVBYtMJMR5JyfO5QCXo4ihaXe2AMJFtv1OhgXl3Ln5BYwSKTWpuBrO7jIz7x8WfiiRodEXk+9W3AZqy390Uk/cAOsJ7lp9VLa80VSx/pGoJ98z61Dg7jsAzsDkaKWIPabbuGysJljuuv2H2fHQvOaH1hunDw9jDMIy2zN4iErrQ0FC+J2oYx3/uo+dnwMoIQP4XeGkiG77mQ0wjt521csXEN/c6ulRc2kIhw==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "0"
      name: bot-discord-spotify
      namespace: bot-discord
    type: Opaque

