apiVersion: v1
kind: Service
metadata:
  name: lavalink
  namespace: bot-discord
  labels:
    app: lavalink
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: ClusterIP
  selector:
    app: lavalink
  ports:
    - name: http
      port: 2333
      targetPort: http
      protocol: TCP
