apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bot-discord-db-credentials
  namespace: bot-discord
spec:
  secretStoreRef:
    name: bot-discord-db
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: bot-discord-db-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgresql://{{ .username }}:{{ .password }}@postgres.bot-discord-db.svc.cluster.local:5432/{{ .database }}"
  data:
    - secretKey: username
      remoteRef:
        key: postgres-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: postgres-credentials
        property: password
    - secretKey: database
      remoteRef:
        key: postgres-credentials
        property: database
